// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OrganizationMaster.Data;
using OrganizationMaster.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OrganizationMaster.Models
{
    public partial class Tblbranchmaster
    {
        [Required]
        public int? OraganizationId { get; set; }
        public int BranchId { get; set; }

        [StringLength(20 , ErrorMessage ="BranchName is too long")]
        public string BranchName { get; set; }

        [Phone]
        public string PhoneNumber { get; set; }

        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public string Fax { get; set; }

        [Required]
        public int? CityId { get; set; }

        [StringLength(8)]
        public string ZipCode { get; set; }

        [Required]
        public string Address { get; set; }

        [Required]
        public string Note { get; set; }
        public bool? IsActive { get; set; }
    }
}


