// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OrganizationMaster.Models
{
    public partial class Tblcountry
    {
        public int CountryId { get; set; }

        [StringLength(15, ErrorMessage ="CountryName is too long")]
        public string CountryName { get; set; }
    }
}