// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace OrganizationMaster.Models
{
    public partial class USP_State_ByIdResult
    {
        public int Country_Id { get; set; }
        public string CountryName { get; set; }
        public int? State_Id { get; set; }
        public string StateName { get; set; }
    }
}
