// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace OrganizationMaster.Models
{
    public partial class USP_Organization_ByIdResult
    {
        public int Oraganization_Id { get; set; }
        public string OraganizationName { get; set; }
        public int City_Id { get; set; }
        public string CityName { get; set; }
        public string RegistrationNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Prefix { get; set; }
        public string ZipCode { get; set; }
        public string Address { get; set; }
        public bool IsActive { get; set; }
    }
}
