// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace OrganizationMaster.Models
{
    public partial class USP_Department_ByIdResult
    {
        public int? Oraganization_Id { get; set; }
        public string OraganizationName { get; set; }
        public int? Branch_Id { get; set; }
        public string BranchName { get; set; }
        public int Department_Id { get; set; }
        public string DepartmentName { get; set; }
        public bool IsActive { get; set; }
    }
}
